### ISSUE TITLE
NPC icon for Dr Unne

### ISSUE THREAD

**Issue by tetron** [bdjeffyp/ffr-tracker#5]
Would be helpful to be able to record whether the slab has been turned in or not, to help avoid taking a long walk to Leifen with the slab but no language skills.

**Comment by bdjeffyp** [comment]
Good call! I noticed in some of the streamed races that the tracker they use does some form of displaying that a turned in item was done. It definitely makes sense in regards to the SLAB/Rosetta Stone here. I'll look at what I can do to make this happen (a checkmark on the SLAB icon, add Dr. Unne to the NPCs, etc).

**Comment by bdjeffyp** [comment]
All set! Dr. Unne has been added to the bottom row of NPCs, between the blacksmith and the Lefeinian. Enjoy and thanks for the feedback!

**Comment by tetron** [comment]
Awesome, thank you so much!   When will it go live on http://bdjeffyp.github.io/ffr-tracker/ ?

**Comment by bdjeffyp** [comment]
Shouldn't be more than a few minutes. The bot takes care of the push to my Github pages for me but doesn't take too long.

**Comment by bdjeffyp** [comment]
Ok! Just verified that it is live now. 👍
