### ISSUE TITLE
NPC icons have stray pixels

### ISSUE THREAD

**Issue by tetron** [bdjeffyp/ffr-tracker#9]
Several NPC icons now have stray pixels from adjacent icons on the sprite sheet, it looks the clipping boxes are slightly off.  (This is on Firefox if it makes a difference).

**Comment by bdjeffyp** [comment]
Hmm... yeah, I'm not seeing it in Edge/Chrome. @tetron, did this start occurring after the Titan was added? Can you share a screen shot or two of what you are seeing?

**Comment by tetron** [comment]
Here's what I'm seeing:

![ffr-tracker-screenshot](https://user-images.githubusercontent.com/1316612/103158758-71331280-478f-11eb-882e-2db9f41bbc2d.png)

It turns out this is actually being caused by page zoom.  I had the page shrunk to 80%.  When I adjust to 100%, it looks fine, no stray pixels.  So, not really a bug, although maybe there's a different way to clip out the sprites that doesn't have this problem.  Maybe you could use SVG instead of CSS?
